import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";

export default function Home() {
  const [image, setImage] = useState(null);
  const [createObjectURL, setCreateObjectURL] = useState(null);

  const uploadToClient = (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];

      setImage(i);
      setCreateObjectURL(URL.createObjectURL(i));
    }
  };

  const uploadToServer = async (event) => {
    const body = new FormData();
    body.append("file", image);
    console.log(image);
    const response = await fetch("/api/file", {
      method: "POST",
      body
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Motion Moment NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Motion Moment NFT
        </h1>
        <div>
         <Image src="https://raw.githubusercontent.com/kurotaky-sandbox/motion-moment-nft/main/public/MotionMoment.png" alt="Motion Moment Logo" width={400} height={400} />
        </div>

        <p className={styles.description}>
          Upload sensor data at the moment of movement to NFT!
        </p>

          <div>
            <div>
              <h4>Select File</h4>
              <input type="file" name="myFile" onChange={uploadToClient} />
              <button
                className="btn btn-primary"
                type="submit"
                onClick={uploadToServer}
              >
                Create NFT
              </button>
            </div>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://polygontokyohack.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          polygontokyohack
        </a>
      </footer>
    </div>
  )
}
